[ru]
about.heading = "Обо мне"
edu.heading = "Образование"
work.heading = "Опыт"
skills.heading = "Навыки"
projects.heading = "Проекты"
languages.heading = "Языки"
remote = "Удалённо"

fullname = "Набойщиков Артемий"
position = "Frontend Разработчик / Vue"
location = "Москва / Удалённо"

[en]
about.heading = "About Me"
edu.heading = "Education"
work.heading = "Work Experience"
skills.heading = "Skills"
projects.heading = "Projects"
languages.heading = "Languages"
remote = "Remote"

fullname = "Artemiy Naboishchikov"
position = "Frontend Developer / Vue"
location = "Moscow / Remote"

[es]
about.heading = "Sobre mí"
edu.heading = "Educación"
work.heading = "Experiencia Laboral"
skills.heading = "Habilidades"
projects.heading = "Proyectos"
languages.heading = "Idiomas"
remote = "Remoto"

fullname = "Artemiy Naboishchikov"
position = "Desarrollador Frontend / Vue"
location = "Moscú / Remoto"

[common]
email = "mrart111@mail.ru"
telegram = "t.me/nartemiy"
github = "github.com/Artemiy111"
phone = { ru = "+7 987 106-04-13", en = "", es = "" }

[common.links]
nuxt-ui = {dest = "https://github.com/nuxt/ui/issues?q=author%3AArtemiy111", body = "@nuxt/ui"}
shadcn-vue = {dest = "https://github.com/unovue/shadcn-vue/issues?q=author%3AArtemiy111", body = "shadcn-vue"}
zod = {dest = "https://github.com/colinhacks/zod/issues?q=author%3AArtemiy111", body = "zod"}
vue-forge = {dest = "https://vuejsforge.com", body = "Vue Forge"}

[location.moscow]
ru = "Москва"
en = "Moscow"
es = "Moscú"

# [location.remove]
# ru = "Удалённо"
# en = "Remote"
# es = "Remoto"

# [[edu.info]]
# institution.ru = "МГТУ «СТАНКИН»"
# institution.en = "Moscow State Technological University STANKIN"
# institution.es = "Universidad Tecnológica Estatal de Moscú STANKIN"
# degree.ru = "Программная инженерия"
# degree.en = "Software Engineering"
# degree.es = "Ingeniería de Software"
# dates = "2022 -- 2026"
# location = "moscow"
